### ISSUE TITLE
Use env for managing secrets

### ISSUE THREAD

**Issue by maybejustmaybe** [bedstuystrong/automation_prime#14]
The config system is a convenient way to manage settings that differ for each environment; however, it isn't a secure way to manage secrets. Either we move away from the config infra completely or integrate env into the existing system.

If we want to integrate env, we could create a new `Env` type to our config infra that reads the environment variable name from the `configs/<config>.json` entry (e.g. `$GOOGLE_API_KEY`) and loads the actual value from the environment.

**Comment by leifwalsh** [comment]
could maybe use https://github.com/sloria/environs once we know what the variable names are
