### ISSUE TITLE
Member hub authentication

### ISSUE THREAD

**Issue by maybejustmaybe** [bedstuystrong/automation_prime#22]
We are using Auth0 to log in users to the members hub. We use the airtable members table to as the source of truth for members.
- [x] Setup Auth0
- [x] Integrate Auth0 into the member hub
- [ ] Register new members with Auth0 (in `member.py:on_new`)
- [ ] Integrate upstream authentication provider support

**Comment by cubeghost** [comment]
@maybejustmaybe what does "Integrate upstream authentication provider support" mean here? the authentication provider we're using is "passwordless" email (and in the future SMS), which is built into Auth0

**Comment by cubeghost** [comment]
details on registering new members in Auth0:
- authenticate with Auth0 Management API (involves [annoying token refresh process](https://auth0.com/docs/tokens/management-api-access-tokens#automate-the-process) 🙃)
- `POST` to the create users endpoint `${AUTH0_DOMAIN}/api/v2/users`
```json
{
  "connection": "email",
  "email": "user@example.com",
  "name": "Person Name"
}
```
...that's it, most of the work will be in implementing the token refresh I expect

**Comment by cubeghost** [comment]
discussed w/ @maybejustmaybe and we can probably store the short-lived token in google cloud's secret manger

prior art:
https://dev.to/googlecloud/using-secrets-in-google-cloud-functions-5aem

infra requirements for the above just seem like giving the default cloud function service account the correct secret accessor/manager roles/permissions
